### PR TITLE
blog/2023: Add Crimson Multi-core Scalability Blog

### PR DESCRIPTION
**Pull request by ljx023**
Signed-off-by: Jianxin Li <jianxin1.li@intel.com>

### CODE REVIEW

**Comment by Thingee** [comment]
jenkins retest this please

**Comment by Thingee** [comment]
@akraitman, the build preview seems to have failed? 

https://crimson-multi-core-scalability-blog.ceph.io/

**Review by athanatos — APPROVED** [review]

**Comment by ljx023** [comment]
> @akraitman, the build preview seems to have failed?
> 
> https://crimson-multi-core-scalability-blog.ceph.io/

@Thingee , I fix this problem(wrong date format) and local run successfully. 

I also update the date and modify the format of reference.

**Review by cyx1231st — APPROVED** [review]
@Thingee is there anything else to do for the merge?

**Comment by Thingee** [comment]
Thank you, everyone, for your time on this post!

**Pull request merged**
