### PR TITLE
community/jobs: Add job page

### PR DESCRIPTION
**Pull request by Thingee**

### CODE REVIEW

**Comment by Thingee** [comment]
For some reason, the getJobs filter I created won't register.

**Comment by Thingee** [comment]
@Pete-Robelou, I can't seem to register a new filter? Is there something else I'm supposed to change?

**Comment by Pete-Robelou** [comment]
> @Pete-Robelou, I can't seem to register a new filter? Is there something else I'm supposed to change?

New filters need to be added to `eleventy.js` under the filters section.

So in this case you'd need to add **eleventyConfig.addFilter('getJobs', require(`${filtersDir}/getJobs.js`));**.

```
// Filters
  const filtersDir = `./src/_11ty/filters`;
  eleventyConfig.addFilter('chunkByYear', require(`${filtersDir}/chunkByYear.js`));
  eleventyConfig.addFilter('cleanCardContent', require(`${filtersDir}/cleanCardContent.js`));
  eleventyConfig.addFilter('cleanSearchRaw', require(`${filtersDir}/cleanSearchRaw.js`));
  eleventyConfig.addFilter('endsWith', require(`${filtersDir}/endsWith.js`));
  eleventyConfig.addFilter('formatDate', require(`${filtersDir}/formatDate.js`));
  eleventyConfig.addFilter('formatDateRange', require(`${filtersDir}/formatDateRange.js`));
  eleventyConfig.addFilter('getArticleType', require(`${filtersDir}/getArticleType.js`));
  eleventyConfig.addFilter('getCollectionByTag', require(`${filtersDir}/getCollectionByTag.js`));
  eleventyConfig.addFilter('getCollectionTags', require(`${filtersDir}/getCollectionTags.js`));
  eleventyConfig.addFilter('getItems', require(`${filtersDir}/getItems.js`));
  eleventyConfig.addFilter('getItemsByLocale', require(`${filtersDir}/getItemsByLocale.js`));
  eleventyConfig.addFilter('getItemsInFuture', require(`${filtersDir}/getItemsInFuture.js`));
  eleventyConfig.addFilter('getItemsInPast', require(`${filtersDir}/getItemsInPast.js`));
  eleventyConfig.addFilter('getJobs', require(`${filtersDir}/getJobs.js`));
  eleventyConfig.addFilter('getSingleDigitFromDate', require(`${filtersDir}/getSingleDigitFromDate.js`));
  eleventyConfig.addFilter('isInFuture', require(`${filtersDir}/isInFuture.js`));
  eleventyConfig.addFilter('objectValues', require(`${filtersDir}/objectValues.js`));
  eleventyConfig.addFilter('randomize', require(`${filtersDir}/randomize.js`));
  eleventyConfig.addFilter('removeHtml', require(`${filtersDir}/removeHtml.js`));
  eleventyConfig.addFilter('removeTags', require(`${filtersDir}/removeTags.js`));
  eleventyConfig.addFilter('startsWith', require(`${filtersDir}/startsWith.js`));
  eleventyConfig.addFilter('truncate', require(`${filtersDir}/truncate.js`));
```

**Comment by liewegas** [comment]
It could say "email ___ or open a pull request" and link to ``https://github.com/ceph/ceph.io/edit/main/src/en/community/jobs/jobs.json``

**Comment by Thingee** [comment]
Closing since #320 resolves the issue.

**Pull request merged**
