### PR TITLE
Updated IBM logo to correct version.

### PR DESCRIPTION
**Pull request by bensternthal**

### CODE REVIEW

**Comment by neha-ojha** [comment]
https://fix-ibm-logo.ceph.io/en/news/blog/2024/ibm-cephalocon-blog-2024/ - not sure there is a way to fix the resolution, but better than before!

**Comment by bensternthal** [comment]
Yikes it's huge, i can fix

**Comment by bensternthal** [comment]
@neha-ojha ok updated, if this looks good please approve and I can merge. 

https://fix-ibm-logo.ceph.io/en/news/blog/2024/ibm-cephalocon-blog-2024/

**Review by neha-ojha — APPROVED** [review]
https://fix-ibm-logo.ceph.io/en/news/blog/2024/ibm-cephalocon-blog-2024/ - much better

nit: you could squash the commits into one commit

**Pull request merged**
