### PR TITLE
community/events: Adding Ceph Days India 2024!

### PR DESCRIPTION
**Pull request by gauravsitlani**

### CODE REVIEW

**Comment by gauravsitlani** [comment]
@Thingee please review

**Comment by gauravsitlani** [comment]
@ideepika PTAL as well

**Review by neha-ojha — APPROVED** [review]
LGTM!

**Comment by gauravsitlani** [comment]
@neha-ojha thanks for the review, can you please take a look again I have updated Clyso in the sponsor information for the event.
cc @ideepika @Thingee

**Comment by anthonyeleven** [comment]
Quite the auspicious PR number ;)

**Pull request merged**
