### PR TITLE
Font loading optimisations

### PR DESCRIPTION
**Pull request by adamduncan**
Testing font loading strategies to improve performance metrics

### CODE REVIEW

**Comment by adamduncan** [comment]
Adding `preconnect` as per Google Fonts "Use on the web" snippet (240c150) brought the font loading forward by ~1.3s

Screenshot 2021-06-22 at 15 58 46

**Comment by adamduncan** [comment]
Also switched order of Google font stylesheet and our own, which when combined with our preconnect change takes our Performance score on Lighthouse Audit from 87 to 94 (with speed index improving from 2.7s to 2.0s) 👀

**Comment by adamduncan** [comment]
@Pete-Robelou I'm happy with this as an enhancement on our existing setup. Thoughts?

**Review by Pete-Robelou — APPROVED** [review]
I like it!

A super simple tweak but results in improved performance 👍

**Pull request merged**
