### PR TITLE
Adjust Foundation Member Logos

### PR DESCRIPTION
**Pull request by jasonvds**
All logos were set to 200x200 during initial build of ceph.io per 8b6cd70d595a0ec7007e2b7bdaf83fbf7adebe97

Subsequent logo uploads have been across a variety of sizes which affects the way they are rendered and pages, such as https://ceph.io/en/foundation/members/ are affected.

Logos have been resized, to a minimum of 72dpi and set to 200x200px

### CODE REVIEW

**Comment by ljflores** [comment]
Hey @jasonvds, this change looks good. However, the site compile check doesn't run for contributors outside the ceph org right now -- while we're fixing that, I raised #741, which is the same as your PR, but so we can confirm it compiles.

**Comment by gauravsitlani** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
jenkins retest

**Comment by ljflores** [comment]
Hi @jasonvds, the site compile check won't run for people outside the ceph org, so I raised the PR again here: #762.

**Pull request closed without merging**
