### PR TITLE
Add 2024 Cephalocon IBM blog

### PR DESCRIPTION
**Pull request by zdover23**
Add a 2024 Cephalocon IBM blog post to the ceph.io website, as requested by Dan van der Ster and Jill Lovato.

### CODE REVIEW

**Review by gauravsitlani — APPROVED** [review]

**Comment by gauravsitlani** [comment]
hey @zdover23 the site compilation failed here

**Comment by gauravsitlani** [comment]
jenkins retest this please

**Comment by zdover23** [comment]
> hey @zdover23 the site compilation failed here
> 
> 

I know. I reported it two weeks ago.

**Comment by ljflores** [comment]
jenkins retest

**Comment by ljflores** [comment]
Hey @zdover23! There were a few things that were causing the site compile failure. I removed the quotes from Title, Author, Date, and Tags, and I also made the tags lowercase and all one word.

**Comment by ljflores** [comment]
https://wip-doc-2024-11-23-ibm-cephalocon-blog-post.ceph.io/en/news/blog/2024/ibm-cephalocon-blog-2024/

**Review by ljflores — APPROVED** [review]

**Pull request merged**
