### PR TITLE
community/events: Adding Ceph Days India!

### PR DESCRIPTION
**Pull request by Thingee**

### CODE REVIEW

**Comment by Thingee** [comment]
@zdover23 please merge tomorrow once we have the additional dates from Gaurav. He should be updating this PR later so that we can announce this event tomorrow at Ceph Days NYC.

**Comment by zdover23** [comment]
> @zdover23 please merge once we have the additional dates from Gaurav. He should be updating this PR later so that we can announce this event tomorrow at Ceph Days NYC.

I'll keep an eye out for the additional dates. I'll make the merge as soon as the update is in.

**Comment by Thingee** [comment]
Preview https://ceph-days-india.ceph.io/en/community/events/2023/ceph-days-india/#

**Comment by veera-raghava-reddy** [comment]
@Thingee @zdover23 The info in the PR related to IBM location and event dates are correct.

**Comment by gauravsitlani** [comment]
Looks good, we'll finalize the dates and share here.

**Review by zdover23 — APPROVED** [review]

**Pull request merged**
