### PR TITLE
doc/releases: 14.2.22 Release Notes

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@djgalloway and what about https://github.com/ceph/ceph/pull/41958 ?

**Comment by djgalloway** [comment]
> @djgalloway and what about [ceph/ceph#41958](https://github.com/ceph/ceph/pull/41958) ?

That PR gets rendered at docs.ceph.com.  This PR gets rendered at ceph.io.

**Comment by djgalloway** [comment]
I needed to get the release notes out today.  The wrong date is fine for the time being.  Suggest rebasing and deleting my commits then maybe changing the branch and PR title.  Or just starting over in a new branch.

**Comment by adamduncan** [comment]
Agree. Happy to close this one out, and we can start a new PR for #241

**Pull request closed without merging**
