### PR TITLE
ceph.io/contribute: add contribute video

### PR DESCRIPTION
**Pull request by zdover23**
This PR adds the Youtube video that explains how
to contribute to the Ceph community. I've put it here
in iframe html tags, but for some reason they don't work
within the website.

Maybe we can boot this to someone with greater understanding
of embedding video in this IA.

Signed-off-by: Zac Dover <zac.dover@gmail.com>

### CODE REVIEW

**Comment by zdover23** [comment]
> Hey @zdover23, great to see content coming in +1
> 
> FYI: A recent update landed that gives us a YouTube embed shortcode to leverage throughout the site. See updated docs in [README](https://github.com/ceph/ceph.io/tree/develop#shortcodes).
> 
> Might be a good one to test it out on here?

Thanks, Adam. I'll give it a go.

**Comment by zdover23** [comment]
The shortcode seems to work as well as iframes, but firefox won't let me test the embedded video locally. I don't know what's going on here, but the information about the video is securely in this commit.

**Comment by Pete-Robelou** [comment]
> The shortcode seems to work as well as iframes, but firefox won't let me test the embedded video locally. I don't know what's going on here, but the information about the video is securely in this commit.

@zdover23 I have checked this locally in FireFox and all is working as expected, could you clarify the issue you were having?

**Comment by zdover23** [comment]
Pete, it's working now, so my earlier comment is moot.

**Pull request merged**
