### PR TITLE
news/blog: Newsletter for March 2022

### PR DESCRIPTION
**Pull request by Thingee**
First pass

### CODE REVIEW

**Comment by Thingee** [comment]
@dabukalam @anthonyeleven @ubi2go @emenguy @gauravsitlani @xiaoquqi anything else to add?

**Comment by anthonyeleven** [comment]
Maybe mention that Cephalocon PDX has been postponed?

**Comment by dvanders** [comment]
Should probably add the Quincy RC now that it's out yesterday

**Comment by gh-Devin** [comment]
It looks very good, I am looking forward to the release, and I will translate it into Chinese for dissemination：）

**Comment by Thingee** [comment]
> Maybe mention that Cephalocon PDX has been postponed?

I added a reminder in the upcoming conferences linking to the past newsletter that mentioned it. I wish I knew what dates are decided to have more of an update.

> 

Thanks @gh-Devin for the review and for translating the notes for others.

**Comment by Thingee** [comment]
Thanks everyone for the help!

**Pull request merged**
