### PR TITLE
blog: Fix broken image links

### PR DESCRIPTION
**Pull request by djgalloway**
Fixes: https://github.com/ceph/ceph.io/issues/251

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
https://251.ceph.io/en/news/blog/2018/new-dashboard-landing-page-nautilus-merged/

**Comment by djgalloway** [comment]
Turns out there's dozens of these.  DNM yet.

**Comment by djgalloway** [comment]
I went back and fixed all the posts through 2017 that had "wp-content" in them.

For 2016 and earlier, the images aren't in the expected paths.  I un`tar`red the old pre-hack website and they're not there either.

**Comment by adamduncan** [comment]
Awesome, @djgalloway. That's a massive improvement 👍

**Review by jdurgin — APPROVED** [review]
thanks for all the updates David!

**Pull request merged**
