### PR TITLE
developers/google-summer-of-code: Updating page for 2023

### PR DESCRIPTION
**Pull request by Thingee**
Signed-off-by: Mike Perez <thingee@gmail.com>

### CODE REVIEW

**Comment by Thingee** [comment]
https://gsoc-2023.ceph.io/en/developers/google-summer-of-code/
http://localhost:8080/en/developers/contribute/

**Comment by Thingee** [comment]
This is needed for our application submission, which is due today.

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
> This is needed for our application submission, which is due today.

We have time to add this year's projects later, right?

**Comment by Thingee** [comment]
> > This is needed for our application submission, which is due today.
> 
> We have time to add this year's projects later, right?

Yes, @alimaredia  announced it on the mailing list and will provide them.

**Pull request merged**
