### PR TITLE
Update Community Calendar embed

### LINKED ISSUE #297: Community calendar iframe doesn't seem to render properly
Tested in Chrome and Firefox on MacOS and neither work for me. Maybe it's just a calendar permissions thing?

Screenshot 2021-11-02 at 17 27 23

### PR DESCRIPTION
**Pull request by adamduncan**
- I believe this is the correct iframe `src` for Ceph Community Calendar (@Thingee to confirm)
- Minor styling: Full-width, and margins
- Fix unlinked "Virtual meetings" jumplink

Fixes #297

### CODE REVIEW

**Comment by adamduncan** [comment]
Further to the embed URL, I think we might need to update the CSP to allow for embeds from Google domains?

@djgalloway, is that something you'd be able to chip in on for this PR? Thanks

```
Content Security Policy: The page's settings blocked the loading of a resource at https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FLos_Angeles&src=OXRzOWM3bHQ3dTF2aWMyaWp2dnFxbGZwbzBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%239E69AF ("default-src").
```

**Comment by djgalloway** [comment]
> https://calendar.google.com

Done!

**Comment by adamduncan** [comment]
Nice! Thanks, @djgalloway 

@Thingee, happy for you to merge if you're happy with the amended calendar embed: https://297-calendar-embed.ceph.io/en/community/meetups/

**Comment by Thingee** [comment]
LGTM, thanks for the help @adamduncan!

**Pull request merged**
